### ISSUE TITLE
Unable to scan

### ISSUE THREAD

**Issue by tminus44** [mailinneberg/BlueBorne#10]
All pre-reqs met. Ran build.sh and "Building Complete!" was returned. I am able to open the GUI interface but when I click start scan I get error box:

Traceback (most recent call last):
File "blueborn.py", line 436, in StartInquiryScan
self.monscreen.DeleteRows(0,self.monscreen.GetNumberRows(),True)
File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/grid.py", line 1277, in DeleteRows
return _grid.Grid_DeleteRows(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "Assert failure" failed at ../src/generic/grid.cpp(1392) in DeleteRows(): Called wxGridStringTable::DeleteRows(pos=0, N=0)
Pos value is invalid for present table with 0 rows

**Comment by ghost** [comment]
Its fake bro all he did was steal Bluemaho and rename it and a shitty job at that.
