### ISSUE TITLE
Cannot run.

### ISSUE THREAD

**Issue by ghost** [mailinneberg/BlueBorne#11]
Cannot run. Environment: Ubuntu
> ➜  BlueBorne python blueborn.py 
Traceback (most recent call last):
  File "blueborn.py", line 1350, in <module>
    ReadDefaultConfiguration(CONFIG_FILENAME)
  File "blueborn.py", line 1283, in ReadDefaultConfiguration
    file_c = open(defconf.theme+pair[1],'r')
IOError: [Errno 2] No such file or directory: 'config/themes/maho/colors'

**Comment by LambdaSoft** [comment]
I have the same error

**Comment by pieterhouwen** [comment]
you need to rename the config/themes/coderunner to maho
