### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by JockerZeus** [mailinneberg/BlueBorne#12]
Traceback (most recent call last):
  File "blueborn.py", line 436, in StartInquiryScan
    self.monscreen.DeleteRows(0,self.monscreen.GetNumberRows(),True)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/grid.py", line 1277, in DeleteRows
    return _grid.Grid_DeleteRows(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "Assert failure" failed at ../src/generic/grid.cpp(1390) in DeleteRows(): Called wxGridStringTable::DeleteRows(pos=0, N=0)
Pos value is invalid for present table with 0 rows

plz help thx

**Comment by AntonisMaxhtec** [comment]
same prob here ;(
